# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19ef7a65afee7c0b221aeaa7036dd775e6609a2edfbaa33e54e0a87d54d2e50daefa4899d7a8136e9640d1c799843815ed1e1b6ee5aaa6aa48ec131e70686b60

test:
  secret_key_base: a121fc4e2f540c5454995e44fcb6f0b3999857cfa4ca1012664ea8d28bdb9d53b126b5fd14e46db7f365577c5b72f80d6b4744bd7a4f814c21b865f7c6ab499c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
